variables:
    PROJECT_NAME: 'feidee-auto-bot'

stages:
    - deploy

docker-deploy:
    stage: deploy
    script:
        - docker build -t $PROJECT_NAME:latest .
        - if [ $(docker ps -aq --filter name=$PROJECT_NAME) ]; then docker rm -f $PROJECT_NAME;fi
        - docker run -d --restart=always -e TZ=Asia/Shanghai -v /root/nas/docker/$PROJECT_NAME/config:/app/config -v /root/nas/docker/$PROJECT_NAME/logs:/app/logs -v /root/nas/docker/$PROJECT_NAME/data:/app/data --name $PROJECT_NAME $PROJECT_NAME:latest
