image: docker:latest

variables:
    PROJECT_NAME: 'feidee-auto-bot'

stages:
    - build

docker-build:
    stage: build
    image: docker:latest
    script:
        - docker build -t $PROJECT_NAME:latest .
        - if [ $(docker ps -aq --filter name=$PROJECT_NAME) ]; then docker rm -f $PROJECT_NAME;fi
        - docker run -d --restart=always -e TZ=Asia/Shanghai -p 20001:80 -v /root/nas/docker/$PROJECT_NAME/credentials.json:/app/credentials.json -v /root/nas/docker/$PROJECT_NAME/logs:/app/logs -v /root/nas/docker/$PROJECT_NAME/data:/app/data -v /root/nas/docker/$PROJECT_NAME/images:/app/images --name $PROJECT_NAME $PROJECT_NAME:latest
    only:
        - tags
    tags:
        - nuc