categories:
    早午晚餐:
        - 大米先生
        - 饿了么
        - 美团
    茶水饮料:
        - 星巴克
        - 咖啡
        - 茶百道
        - 全家
        - 罗森
        - 蜜雪冰城
        - 售货机
        - Coffee
        - COFFEE
    水果零食:
        - 百果园
    公共交通:
        - 铁路
        - 公共交通卡
    私家车费用:
        - 中国石化
    打车租车:
        - 滴滴
    水电煤气:
        - 电力公司
        - 城投水务
        - 上海燃气
memos:
    电费:
        - 电力公司
    水费:
        - 城投水务
    燃气费:
        - 上海燃气
    iCloud 会员:
        - 云上艾珀
    叮咚买菜:
        - 壹佰米
    饿了么:
        - 拉扎斯
    全家:
        - 福满家
    罗森:
        - LAWSON
    哈啰:
        - 钧正
